# Generated by Django 5.2.13 on 2026-04-29 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("jobs", "0001_initial"),
        ("targets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Discovery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cidr", models.CharField(max_length=64)),
                ("ports", models.JSONField(default=list)),
                ("include_default_ports", models.BooleanField(default=False)),
                ("status", models.CharField(default="PENDING", max_length=20)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("error", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "async_job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discovery",
                        to="jobs.asyncjob",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DiscoveredEndpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("host", models.CharField(max_length=253)),
                ("port", models.PositiveIntegerField()),
                ("transport", models.CharField(default="TCP", max_length=8)),
                ("detected_protocol", models.CharField(max_length=32)),
                ("suggested_protocol_hint", models.CharField(max_length=16)),
                ("promoted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "target",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="targets.target",
                    ),
                ),
                (
                    "discovery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="endpoints",
                        to="discoveries.discovery",
                    ),
                ),
            ],
        ),
    ]
