# Generated by Django 5.2.13 on 2026-04-29 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discoveries", "0001_initial"),
        ("jobs", "0003_asyncjob_async_job_kind_status_idx_and_more"),
        ("targets", "0002_target_target_host_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="discoveredendpoint",
            index=models.Index(
                fields=["discovery", "promoted"], name="endpoint_discovery_prom_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="discoveredendpoint",
            index=models.Index(
                fields=["host", "port", "transport"], name="endpoint_natural_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="discovery",
            index=models.Index(
                fields=["status", "-created_at"], name="discovery_status_created_idx"
            ),
        ),
    ]
