# Generated by Codex on 2026-05-04

from django.db import migrations, models


def copy_cidr_to_scope_value(apps, schema_editor):
    Discovery = apps.get_model("discoveries", "Discovery")
    for discovery in Discovery.objects.filter(scope_value="").iterator():
        discovery.scope_value = discovery.cidr
        discovery.save(update_fields=["scope_value"])


class Migration(migrations.Migration):

    dependencies = [
        ("discoveries", "0002_discoveredendpoint_endpoint_discovery_prom_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="discovery",
            name="scope_type",
            field=models.CharField(default="cidr", max_length=16),
        ),
        migrations.AddField(
            model_name="discovery",
            name="scope_value",
            field=models.CharField(default="", max_length=253),
        ),
        migrations.AlterField(
            model_name="discovery",
            name="cidr",
            field=models.CharField(max_length=253),
        ),
        migrations.RunPython(copy_cidr_to_scope_value, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="discovery",
            constraint=models.CheckConstraint(
                condition=models.Q(scope_type__in=["cidr", "ip", "domain"]),
                name="discovery_scope_type_valid",
            ),
        ),
        migrations.AddIndex(
            model_name="discovery",
            index=models.Index(fields=["scope_type", "-created_at"], name="discovery_scope_created_idx"),
        ),
    ]
