# Generated by Codex on 2026-05-04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0004_agent_role"),
        ("discoveries", "0003_discovery_scope_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="discovery",
            name="executor_type",
            field=models.CharField(default="central", max_length=16),
        ),
        migrations.AddField(
            model_name="discovery",
            name="discovery_agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assigned_discoveries",
                to="agents.agent",
            ),
        ),
        migrations.AddConstraint(
            model_name="discovery",
            constraint=models.CheckConstraint(
                condition=models.Q(executor_type__in=["central", "agent"]),
                name="discovery_executor_type_valid",
            ),
        ),
        migrations.AddIndex(
            model_name="discovery",
            index=models.Index(fields=["executor_type", "-created_at"], name="discovery_executor_created_idx"),
        ),
        migrations.AddIndex(
            model_name="discovery",
            index=models.Index(fields=["discovery_agent", "-created_at"], name="discovery_agent_created_idx"),
        ),
    ]
