# Generated by Django 5.2.13 on 2026-04-28 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0001_initial"),
        ("snapshots", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="snapshot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assets",
                to="snapshots.cbomsnapshot",
            ),
        ),
    ]
