# Generated by Django 5.2.13 on 2026-04-29 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0002_asset_snapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="algorithm",
            field=models.CharField(default="", max_length=128),
        ),
        migrations.AddField(
            model_name="asset",
            name="algorithm_family",
            field=models.CharField(default="", max_length=64),
        ),
        migrations.AddField(
            model_name="asset",
            name="asset_class",
            field=models.CharField(default="crypto", max_length=32),
        ),
        migrations.AddField(
            model_name="asset",
            name="asset_type",
            field=models.CharField(default="certificate", max_length=32),
        ),
        migrations.AddField(
            model_name="asset",
            name="natural_key",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.CreateModel(
            name="AssetContextOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sensitivity", models.CharField(blank=True, max_length=16, null=True)),
                ("lifespan_years", models.IntegerField(blank=True, null=True)),
                ("criticality", models.CharField(blank=True, max_length=16, null=True)),
                ("exposure", models.CharField(blank=True, max_length=32, null=True)),
                (
                    "service_role",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("override_keys", models.JSONField(default=list)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="context_override",
                        to="assets.asset",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QualitativeAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=64)),
                ("summary", models.TextField()),
                ("threat_scenarios", models.JSONField(default=list)),
                ("migration_recommendation", models.TextField()),
                ("confidence", models.FloatField(default=0.0)),
                ("generated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qualitative_assessment",
                        to="assets.asset",
                    ),
                ),
            ],
        ),
    ]
