# Generated by Django 5.2.13 on 2026-04-29 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0003_asset_algorithm_asset_algorithm_family_and_more"),
        ("snapshots", "0003_cbomsnapshot_snapshot_created_desc_idx_and_more"),
        ("targets", "0002_target_target_host_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["snapshot", "asset_type"], name="asset_snapshot_type_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["snapshot", "target"], name="asset_snapshot_target_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(fields=["natural_key"], name="asset_natural_key_idx"),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["algorithm_family"], name="asset_algorithm_family_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assetcontextoverride",
            index=models.Index(fields=["asset"], name="asset_context_asset_idx"),
        ),
        migrations.AddConstraint(
            model_name="asset",
            constraint=models.UniqueConstraint(
                fields=("snapshot", "natural_key"),
                name="uniq_asset_snapshot_natural_key",
            ),
        ),
    ]
