# Generated by Django 5.2.13 on 2026-04-30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0004_asset_asset_snapshot_type_idx_and_more"),
        ("snapshots", "0003_cbomsnapshot_snapshot_created_desc_idx_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="asset",
            name="uniq_asset_snapshot_natural_key",
        ),
        migrations.RemoveIndex(
            model_name="asset",
            name="asset_natural_key_idx",
        ),
        migrations.RenameField(
            model_name="asset",
            old_name="natural_key",
            new_name="bom_ref",
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(fields=["bom_ref"], name="asset_bom_ref_idx"),
        ),
        migrations.AddConstraint(
            model_name="asset",
            constraint=models.UniqueConstraint(fields=("snapshot", "bom_ref"), name="uniq_asset_snapshot_bom_ref"),
        ),
        migrations.CreateModel(
            name="AssetDependency",
            fields=[
                (
                    "id",
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("relation_type", models.CharField(default="dependsOn", max_length=32)),
                ("semantic", models.CharField(default="", max_length=64)),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asset_dependencies",
                        to="snapshots.cbomsnapshot",
                    ),
                ),
                (
                    "source_asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dependency_edges",
                        to="assets.asset",
                    ),
                ),
                (
                    "target_asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="depended_by_edges",
                        to="assets.asset",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="assetdependency",
            index=models.Index(fields=["snapshot", "source_asset"], name="asset_dep_source_idx"),
        ),
        migrations.AddIndex(
            model_name="assetdependency",
            index=models.Index(fields=["snapshot", "target_asset"], name="asset_dep_target_idx"),
        ),
        migrations.AddConstraint(
            model_name="assetdependency",
            constraint=models.UniqueConstraint(
                fields=("snapshot", "source_asset", "target_asset", "relation_type"),
                name="uniq_asset_dependency_edge",
            ),
        ),
    ]
