# Generated by Django 5.2.13 on 2026-04-29 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assets", "0003_asset_algorithm_asset_algorithm_family_and_more"),
        ("snapshots", "0002_cbomsnapshot_cbom_json_cbomsnapshot_scan_job_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RiskWeights",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wA", models.FloatField(default=1.0)),
                ("wD", models.FloatField(default=1.0)),
                ("wE", models.FloatField(default=1.0)),
                ("wL", models.FloatField(default=1.0)),
                ("wC", models.FloatField(default=1.0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="RiskScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.FloatField()),
                ("tier", models.CharField(max_length=16)),
                ("factors", models.JSONField(default=dict)),
                ("computed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_scores",
                        to="assets.asset",
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_scores",
                        to="snapshots.cbomsnapshot",
                    ),
                ),
            ],
        ),
    ]
