# Generated by Django 5.2.13 on 2026-04-29 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0004_asset_asset_snapshot_type_idx_and_more"),
        ("risk", "0001_initial"),
        ("snapshots", "0003_cbomsnapshot_snapshot_created_desc_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="riskscore",
            index=models.Index(
                fields=["snapshot", "tier", "-score"],
                name="risk_snapshot_tier_score_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="riskscore",
            index=models.Index(fields=["asset"], name="risk_asset_idx"),
        ),
        migrations.AddConstraint(
            model_name="riskscore",
            constraint=models.CheckConstraint(
                condition=models.Q(("score__gte", 0), ("score__lte", 100)),
                name="risk_score_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="riskscore",
            constraint=models.CheckConstraint(
                condition=models.Q(("tier__in", ["CRITICAL", "HIGH", "MEDIUM", "LOW"])),
                name="risk_tier_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="riskweights",
            constraint=models.CheckConstraint(
                condition=models.Q(("wA__gte", 0.5), ("wA__lte", 2.0)),
                name="risk_weight_wa_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="riskweights",
            constraint=models.CheckConstraint(
                condition=models.Q(("wD__gte", 0.5), ("wD__lte", 2.0)),
                name="risk_weight_wd_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="riskweights",
            constraint=models.CheckConstraint(
                condition=models.Q(("wE__gte", 0.5), ("wE__lte", 2.0)),
                name="risk_weight_we_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="riskweights",
            constraint=models.CheckConstraint(
                condition=models.Q(("wL__gte", 0.5), ("wL__lte", 2.0)),
                name="risk_weight_wl_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="riskweights",
            constraint=models.CheckConstraint(
                condition=models.Q(("wC__gte", 0.5), ("wC__lte", 2.0)),
                name="risk_weight_wc_range",
            ),
        ),
    ]
