no-resolv
no-hosts
domain-needed
bogus-priv
log-queries
log-facility=-

address=/dns.testbed.local/172.31.240.2
address=/web.testbed.local/172.31.240.10
address=/web-ec.testbed.local/172.31.240.10
address=/pqc-tls.testbed.local/172.31.240.11
address=/ssh.testbed.local/172.31.240.12
address=/mqtt.testbed.local/172.31.240.13
address=/ipsec.testbed.local/172.31.240.14
address=/mail.testbed.local/172.31.240.15
address=/db.testbed.local/172.31.240.16
