no-resolv
no-hosts
domain-needed
bogus-priv
log-queries
log-facility=-

address=/dns.testbed.local/172.31.240.2
address=/web.testbed.local/172.31.240.10
address=/web-ec.testbed.local/172.31.240.10
address=/pqc-tls.testbed.local/172.31.240.11
address=/ssh.testbed.local/172.31.240.12
address=/mqtt.testbed.local/172.31.240.13
address=/ipsec.testbed.local/172.31.240.14
address=/mail.testbed.local/172.31.240.15
address=/db.testbed.local/172.31.240.16
address=/api-gateway.testbed.local/172.31.240.21
address=/admin-console.testbed.local/172.31.240.22
address=/mobile-api.testbed.local/172.31.240.23
address=/auth-oidc.testbed.local/172.31.240.24
address=/saml-idp.testbed.local/172.31.240.25
address=/mysql-legacy.testbed.local/172.31.240.26
address=/redis-cache.testbed.local/172.31.240.27
address=/kafka-broker.testbed.local/172.31.240.28
address=/internal-grpc.testbed.local/172.31.240.29
address=/service-mesh-mtls.testbed.local/172.31.240.30
address=/gitlab-runner.testbed.local/172.31.240.31
address=/container-registry.testbed.local/172.31.240.32
address=/artifact-repo.testbed.local/172.31.240.33
address=/vault.testbed.local/172.31.240.34
address=/backup-service.testbed.local/172.31.240.35
address=/monitoring.testbed.local/172.31.240.36
address=/logging.testbed.local/172.31.240.37
address=/legacy-java-app.testbed.local/172.31.240.38
