# Generated by Django 5.2.13 on 2026-04-29 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_scanjob_scanrunlog"),
        ("targets", "0002_target_target_host_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="asyncjob",
            index=models.Index(
                fields=["kind", "status"], name="async_job_kind_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="asyncjob",
            index=models.Index(
                fields=["status", "-created_at"], name="async_job_status_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scanrunlog",
            index=models.Index(
                fields=["async_job", "status"], name="scan_run_job_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scanrunlog",
            index=models.Index(
                fields=["scanner_kind", "status"], name="scan_run_scanner_status_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="asyncjob",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("kind__in", ["scan_job", "discovery", "recompute"])
                ),
                name="async_job_kind_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="asyncjob",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        ["PENDING", "RUNNING", "COMPLETED", "FAILED", "CANCELLED"],
                    )
                ),
                name="async_job_status_valid",
            ),
        ),
    ]
