# Generated by Django 5.2.13 on 2026-04-29 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_asyncjob_async_job_kind_status_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="QueuedTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_name", models.CharField(max_length=128)),
                ("payload", models.JSONField(default=dict)),
                ("status", models.CharField(default="QUEUED", max_length=20)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("available_at", models.DateTimeField(blank=True, null=True)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "async_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queued_tasks",
                        to="jobs.asyncjob",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["status", "available_at"],
                        name="queue_status_available_idx",
                    ),
                    models.Index(
                        fields=["task_name", "status"], name="queue_task_status_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("status__in", ["QUEUED", "RUNNING", "COMPLETED", "FAILED"])
                        ),
                        name="queued_task_status_valid",
                    )
                ],
            },
        ),
    ]
