# Generated by Django 5.2.13 on 2026-04-28 23:58

import apps.targets.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Target",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("host", models.CharField(max_length=253)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "port",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(65535),
                        ]
                    ),
                ),
                ("protocol_hint", models.CharField(max_length=16)),
                ("sni", models.CharField(blank=True, max_length=253, null=True)),
                ("transport", models.CharField(default="TCP", max_length=8)),
                ("agent_enabled", models.BooleanField(default=False)),
                ("agent_url", models.URLField(blank=True, null=True)),
                (
                    "context",
                    models.JSONField(default=apps.targets.models.default_context),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("host", "port", "transport"),
                        name="uniq_target_host_port_transport",
                    )
                ],
            },
        ),
    ]
