# Generated by Django 5.2.13 on 2026-04-29 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("targets", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="target",
            index=models.Index(fields=["host"], name="target_host_idx"),
        ),
        migrations.AddIndex(
            model_name="target",
            index=models.Index(
                fields=["protocol_hint"], name="target_protocol_hint_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="target",
            index=models.Index(
                fields=["agent_enabled"], name="target_agent_enabled_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="target",
            index=models.Index(fields=["-created_at"], name="target_created_desc_idx"),
        ),
        migrations.AddConstraint(
            model_name="target",
            constraint=models.CheckConstraint(
                condition=models.Q(("port__gte", 1), ("port__lte", 65535)),
                name="target_port_range_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="target",
            constraint=models.CheckConstraint(
                condition=models.Q(("transport__in", ["TCP", "UDP"])),
                name="target_transport_valid",
            ),
        ),
    ]
