# Generated by Django 5.2.13 on 2026-04-30 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("targets", "0002_target_target_host_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="target",
            name="display_name",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
