# Generated by Django 5.2.13 on 2026-04-29 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_scanjob_scanrunlog"),
        ("snapshots", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cbomsnapshot",
            name="cbom_json",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="cbomsnapshot",
            name="scan_job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="jobs.scanjob",
            ),
        ),
        migrations.AddField(
            model_name="cbomsnapshot",
            name="serial_number",
            field=models.CharField(default="", max_length=128),
        ),
        migrations.AddField(
            model_name="cbomsnapshot",
            name="summary",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="cbomsnapshot",
            name="validation_errors",
            field=models.JSONField(default=list),
        ),
    ]
