# Generated by Django 5.2.13 on 2026-04-29 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_asyncjob_async_job_kind_status_idx_and_more"),
        ("snapshots", "0002_cbomsnapshot_cbom_json_cbomsnapshot_scan_job_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="cbomsnapshot",
            index=models.Index(
                fields=["-created_at"], name="snapshot_created_desc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cbomsnapshot",
            index=models.Index(fields=["scan_job"], name="snapshot_scan_job_idx"),
        ),
    ]
