# Generated by Django 5.2.13 on 2026-04-30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("snapshots", "0003_cbomsnapshot_snapshot_created_desc_idx_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cbomsnapshot",
            name="cbom_json",
        ),
    ]
