per_listener_settings false
allow_anonymous true

listener 8883 0.0.0.0
protocol mqtt
cafile /mosquitto/certs/mqtt/ca.crt
certfile /mosquitto/certs/mqtt/server.crt
keyfile /mosquitto/certs/mqtt/server.key
