# Generated by Django 5.2.13 on 2026-04-29 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="agent",
            index=models.Index(
                fields=["active", "last_seen"], name="agent_active_last_seen_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agent",
            index=models.Index(fields=["hostname"], name="agent_hostname_idx"),
        ),
    ]
