# Generated by Django 5.2.13 on 2026-04-29 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0002_agent_agent_active_last_seen_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="agent_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="os_distribution",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
