# Generated by Codex on 2026-05-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0003_agent_agent_url_agent_os_distribution"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="hostname",
            field=models.CharField(max_length=253),
        ),
        migrations.AddField(
            model_name="agent",
            name="agent_role",
            field=models.CharField(default="host", max_length=16),
        ),
        migrations.AddConstraint(
            model_name="agent",
            constraint=models.CheckConstraint(
                condition=models.Q(agent_role__in=["host", "discovery"]),
                name="agent_role_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="agent",
            constraint=models.UniqueConstraint(fields=["hostname", "agent_role"], name="agent_hostname_role_uniq"),
        ),
        migrations.AddIndex(
            model_name="agent",
            index=models.Index(fields=["agent_role", "active", "last_seen"], name="agent_role_active_seen_idx"),
        ),
    ]
