# Generated by Codex on 2026-05-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0004_agent_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="agent_runtime_token",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
